#数据源配置
spring:
  datasource:
    url: ${blade.datasource.prod.url}
    username: ${blade.datasource.prod.username}
    password: ${blade.datasource.prod.password}
blade:
  #多团队协作服务配置
  ribbon:
    rule:
      #开启配置
      enabled: true
      #负载均衡优先调用的ip段
      prior-ip-pattern:
        - 192.168.0.*
        - 127.0.0.1
